/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eoLwzuNhK8p
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Arimo } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuLink } from "@/components/ui/navigation-menu"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="fixed top-0 left-0 right-0 z-10 bg-background px-4 py-3 shadow-sm sm:px-6 md:px-8">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="text-lg font-semibold text-foreground" prefetch={false}>
            Portfolio
          </Link>
          <NavigationMenu>
            <NavigationMenuList>
              <NavigationMenuItem>
                <NavigationMenuLink href="/">Home</NavigationMenuLink>
              </NavigationMenuItem>
              <NavigationMenuItem>
                <NavigationMenuLink href="/projects">Projects</NavigationMenuLink>
              </NavigationMenuItem>
              <NavigationMenuItem>
                <NavigationMenuLink href="/blog">Blog</NavigationMenuLink>
              </NavigationMenuItem>
              <NavigationMenuItem>
                <NavigationMenuLink href="/contact">Contact</NavigationMenuLink>
              </NavigationMenuItem>
            </NavigationMenuList>
          </NavigationMenu>
        </div>
      </header>
      <main className="flex-1 mt-16">
        <section className="bg-background py-12 sm:py-16 md:py-20">
          <div className="container mx-auto grid grid-cols-1 gap-8 px-4 sm:px-6 md:grid-cols-2 md:gap-12 md:px-8">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold text-foreground sm:text-4xl md:text-5xl">Welcome to My Portfolio</h1>
              <p className="text-muted-foreground">
                Hi, I'm John Doe, a passionate web developer with a keen eye for design. I specialize in creating
                modern, responsive websites that deliver exceptional user experiences.
              </p>
              <div className="flex gap-4">
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}
                >
                  View Projects
                </Link>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground shadow-sm transition-colors hover:bg-muted focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}
                >
                  Contact Me
                </Link>
              </div>
            </div>
            <div className="overflow-hidden rounded-lg">
              <img
                src="/placeholder.svg"
                width={800}
                height={600}
                alt="Hero Image"
                className="h-full w-full object-cover"
                style={{ aspectRatio: "800/600", objectFit: "cover" }}
              />
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 sm:py-16 md:py-20">
          <div className="container mx-auto px-4 sm:px-6 md:px-8">
            <h2 className="mb-8 text-2xl font-bold text-foreground sm:text-3xl">Featured Projects</h2>
            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3">
              <Link
                href="#"
                className="group block overflow-hidden rounded-lg bg-background shadow-sm transition-all hover:shadow-md"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Project 1"
                  className="h-48 w-full object-cover transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-semibold text-foreground">Project 1</h3>
                  <p className="text-muted-foreground">A brief description of the project.</p>
                </div>
              </Link>
              <Link
                href="#"
                className="group block overflow-hidden rounded-lg bg-background shadow-sm transition-all hover:shadow-md"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Project 2"
                  className="h-48 w-full object-cover transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-semibold text-foreground">Project 2</h3>
                  <p className="text-muted-foreground">A brief description of the project.</p>
                </div>
              </Link>
              <Link
                href="#"
                className="group block overflow-hidden rounded-lg bg-background shadow-sm transition-all hover:shadow-md"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Project 3"
                  className="h-48 w-full object-cover transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-semibold text-foreground">Project 3</h3>
                  <p className="text-muted-foreground">A brief description of the project.</p>
                </div>
              </Link>
            </div>
          </div>
        </section>
        <section className="bg-background py-12 sm:py-16 md:py-20">
          <div className="container mx-auto px-4 sm:px-6 md:px-8">
            <h2 className="mb-8 text-2xl font-bold text-foreground sm:text-3xl">Latest Blog Posts</h2>
            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3">
              <Link
                href="#"
                className="group block overflow-hidden rounded-lg bg-background shadow-sm transition-all hover:shadow-md"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Blog Post 1"
                  className="h-48 w-full object-cover transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-semibold text-foreground">Blog Post 1</h3>
                  <p className="text-muted-foreground">A brief description of the blog post.</p>
                </div>
              </Link>
              <Link
                href="#"
                className="group block overflow-hidden rounded-lg bg-background shadow-sm transition-all hover:shadow-md"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Blog Post 2"
                  className="h-48 w-full object-cover transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-semibold text-foreground">Blog Post 2</h3>
                  <p className="text-muted-foreground">A brief description of the blog post.</p>
                </div>
              </Link>
              <Link
                href="#"
                className="group block overflow-hidden rounded-lg bg-background shadow-sm transition-all hover:shadow-md"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Blog Post 3"
                  className="h-48 w-full object-cover transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-semibold text-foreground">Blog Post 3</h3>
                  <p className="text-muted-foreground">A brief description of the blog post.</p>
                </div>
              </Link>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 sm:py-16 md:py-20">
          <div className="container mx-auto px-4 sm:px-6 md:px-8">
            <h2 className="mb-8 text-2xl font-bold text-foreground sm:text-3xl">Certificates</h2>
            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3">
              <div className="group block overflow-hidden rounded-lg bg-background shadow-sm transition-all hover:shadow-md">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Certificate 1"
                  className="h-48 w-full object-cover transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-semibold text-foreground">Certificate 1</h3>
                  <p className="text-muted-foreground">Description of Certificate 1</p>
                </div>
              </div>
              <div className="group block overflow-hidden rounded-lg bg-background shadow-sm transition-all hover:shadow-md">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Certificate 2"
                  className="h-48 w-full object-cover transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-semibold text-foreground">Certificate 2</h3>
                  <p className="text-muted-foreground">Description of Certificate 2</p>
                </div>
              </div>
              <div className="group block overflow-hidden rounded-lg bg-background shadow-sm transition-all hover:shadow-md">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Certificate 3"
                  className="h-48 w-full object-cover transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-semibold text-foreground">Certificate 3</h3>
                  <p className="text-muted-foreground">Description of Certificate 3</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 sm:py-16 md:py-20">
          <div className="container mx-auto px-4 sm:px-6 md:px-8">
            <h2 className="mb-8 text-2xl font-bold text-foreground sm:text-3xl">Get in Touch</h2>
            <form className="mx-auto max-w-md space-y-4">
              <Input type="text" placeholder="Name" className="w-full" />
              <Input type="email" placeholder="Email" className="w-full" />
              <Textarea placeholder="Message" className="w-full" />
              <Button type="submit" className="w-full">
                Submit
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-background px-4 py-6 shadow-sm sm:px-6 md:px-8">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm text-muted-foreground">&copy; 2024 John Doe. All rights reserved.</p>
          <div className="flex items-center space-x-4">
            <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
              <TwitterIcon className="h-5 w-5" />
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
              <LinkedinIcon className="h-5 w-5" />
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
              <GitlabIcon className="h-5 w-5" />
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function GitlabIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
